### ISSUE TITLE
Scree Plot Title Could be Misleading

### ISSUE THREAD

**Issue by timernst** [StatQuest/pca_demo#1]
https://github.com/StatQuest/pca_demo/blob/e909923880018cb7c226267698708cd277a701b0/pca_demo.R#L29

I think perhaps this is not actually a Scree plot. A scree plot would show the eigenvalues for each principal component. 
https://en.wikipedia.org/wiki/Scree_plot

**Comment by StatQuest** [comment]
Scree plots can show eigenvalues or variances, see: 
https://online.stat.psu.edu/stat555/node/96/
https://stat.ethz.ch/R-manual/R-patched/library/stats/html/screeplot.html
https://analyse-it.com/docs/user-guide/multivariate/scree-plot
https://rdrr.io/bioc/PCAtools/man/screeplot.html
Personally, I find it easier to interpret variances, so that is what I use.

**Comment by timernst** [comment]
Amazing. Thank you for always teaching me new things!
